version: '3'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taxi_ais
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/taxi_ais
    ports:
      - "80:80"

  web:
    image: m4vdoshin/taxi_ais:test
    volumes:
      - media:/taxi_ais/media
      # - /home/logs:/taxi_ais/debug.log
      - .:/taxi_ais
    command: uwsgi --ini /taxi_ais/config/uwsgi/uwsgi.ini
    # ports:
    #   - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=taxi_ais.settings.prod
    depends_on:
      - db
    links:
      - db

  celery-worker:
    image: m4vdoshin/taxi_ais:test
    volumes:
      - media:/taxi_ais/media
    command:
      celery -A taxi_ais worker -l INFO
    environment:
      - DJANGO_SETTINGS_MODULE=taxi_ais.settings.prod
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq

  celery-beat:
    image: m4vdoshin/taxi_ais:test
    volumes:
      - media:/taxi_ais/media
    command:
      celery -A taxi_ais beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DJANGO_SETTINGS_MODULE=taxi_ais.settings.prod
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq

volumes:
  rabbitmq:
    driver: local
  database:
    driver: local
  media:
