version: '3'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taxi_ais
    volumes:
      - database:/var/lib/postgresql/data

  web:
    image: m4vdoshin/taxi_ais:2
    volumes:
      - media:/taxi_ais/media
      - /home/logs:/taxi_ais/debug.log
    command:
      python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  celery-worker:
    image: m4vdoshin/taxi_ais:2
    volumes:
      - media:/taxi_ais/media
    command:
      celery -A taxi_ais worker -l INFO
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq

  celery-beat:
    image: m4vdoshin/taxi_ais:2
    volumes:
      - media:/taxi_ais/media
    command:
      celery -A taxi_ais beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - rabbitmq
    links:
      - db
      - rabbitmq

volumes:
  rabbitmq:
    driver: local
  database:
    driver: local
  media:
