version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taxi_ais
    volumes:
      - database:/var/lib/postgresql/data

  web:
    image: m4vdoshin/taxi_ais:test
    volumes:
      - media:/taxi_ais/media
    command: python manage.py runserver
    environment:
      - DJANGO_SETTINGS_MODULE=taxi_ais.settings.prod
    depends_on:
      - db
    links:
      - db

volumes:
  database:
    driver: local
  media:
    driver: local
