# Generated by Django 4.1.7 on 2023-06-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=33, null=True, verbose_name='Тег в телеграм'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
