# Generated by Django 4.1.7 on 2023-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentstatus',
            options={'verbose_name': 'Статус ДТП', 'verbose_name_plural': 'Статусы ДТП'},
        ),
        migrations.AlterModelOptions(
            name='caraccident',
            options={'verbose_name': 'ДТП', 'verbose_name_plural': 'ДТП'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['organisation'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Затрата', 'verbose_name_plural': 'Затраты'},
        ),
        migrations.AlterModelOptions(
            name='expensestatus',
            options={'verbose_name': 'Статус затраты', 'verbose_name_plural': 'Статусы затрат'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['execution_time'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренда'},
        ),
        migrations.AlterModelOptions(
            name='rentstatus',
            options={'verbose_name': 'Статус аренды', 'verbose_name_plural': 'Статусы аренды'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Тип ТС', 'verbose_name_plural': 'Типы ТС'},
        ),
        migrations.RemoveField(
            model_name='accidentstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='expensestatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rentstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='accidentstatus',
            name='status',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='expensestatus',
            name='status',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rentstatus',
            name='status',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Статус'),
        ),
    ]
