# Generated by Django 4.1.7 on 2023-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_driver_name_alter_driver_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='acceptance_certificate_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/acceptance_certificates/', verbose_name='Акт приема-передачи'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='leasing_contract_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/leasing_contracts/', verbose_name='Договор лизинга'),
        ),
    ]
