# Generated by Django 4.1.7 on 2023-03-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_vehicletype_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
    ]
