# Generated by Django 4.1.7 on 2023-06-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_vehicle_acceptance_certificate_scan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='rent_sum',
        ),
    ]
