# Generated by Django 4.1.7 on 2023-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_alter_vehicletype_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='driver',
            name='patronimic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='driver',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='citizenship',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Залог'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_category',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер прав'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фото паспорта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_validity_period',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фото паспорта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rent_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фото паспорта'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rent_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='residence_place',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Место жительства'),
        ),
    ]
