# Generated by Django 4.1.7 on 2023-03-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_driver_first_name_driver_patronimic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='passport_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер паспорта'),
        ),
    ]
