# Generated by Django 4.1.7 on 2023-03-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_alter_driver_driving_license_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driving_license_category',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Категория'),
        ),
    ]
