# Generated by Django 4.1.7 on 2023-03-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_alter_driver_driving_license_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_id',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='№ двигателя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='leasing_contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ДЛ'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lessor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лизингодатель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='postfix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Постфикс ДЛ'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Префикс ДЛ'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_certificate_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='№ СТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_certificate_scan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Скан СТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_passport_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='№ ПТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_passport_scan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Скан ПТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.vehicletype', verbose_name='Тип ТС'),
        ),
    ]
