# Generated by Django 4.1.7 on 2023-03-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0010_alter_vehicle_color_alter_vehicle_engine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_certificate_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='СТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_passport_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ПТС'),
        ),
    ]
