# Generated by Django 4.1.7 on 2023-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_alter_vehicle_registration_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
