# Generated by Django 4.1.7 on 2023-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_vehicle_leasing_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер полиса'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_series',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Серия полиса'),
        ),
    ]
