# Generated by Django 4.1.7 on 2023-03-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_alter_client_business_activity_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='organisation',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Организация'),
        ),
    ]
