# Generated by Django 4.1.7 on 2023-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_alter_client_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bank_name',
            field=models.CharField(max_length=150, verbose_name='Банк'),
        ),
    ]
