# Generated by Django 4.1.7 on 2023-03-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0017_alter_client_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_taxpayer_id',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='postfix',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='prefix',
        ),
        migrations.AddField(
            model_name='caraccident',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='references.contractor', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='client',
            name='documents',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Сканы документов'),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='rent',
            name='balance',
            field=models.FloatField(null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='rent',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='references.contractor', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='has_gas_cylinder_equipment',
            field=models.BooleanField(blank=True, default=False, verbose_name='ГБО'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='rent_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='client',
            name='organisation',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='renting_date',
            field=models.DateField(db_index=True, verbose_name='Дата аренды'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фото прав'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_certificate_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ СТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_passport_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ ПТС'),
        ),
    ]
