# Generated by Django 4.1.7 on 2023-03-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0018_rename_client_taxpayer_id_order_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='passport_photo',
        ),
        migrations.CreateModel(
            name='DriverPassportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='driver_passports/', verbose_name='Фото паспорта')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.driver', verbose_name='Водитель')),
            ],
        ),
    ]
