# Generated by Django 4.1.7 on 2023-03-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0019_remove_driver_passport_photo_driverpassportphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driving_license_photo',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='photo_link',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='rent_photo',
        ),
        migrations.AlterField(
            model_name='driverpassportphoto',
            name='photo',
            field=models.ImageField(upload_to='drivers/passports/', verbose_name='Фото паспорта'),
        ),
        migrations.CreateModel(
            name='VehiclePassportScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='vehicles/Сканы_ПТС', verbose_name='Скан ПТС')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.vehicle', verbose_name='ТС')),
            ],
        ),
        migrations.CreateModel(
            name='RentingContractPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='drivers/renting_contracts/', verbose_name='Фото договора аренды')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.driver', verbose_name='Водитель')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCertificateScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='vehicles/Сканы_СТС', verbose_name='Скан СТС')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.vehicle', verbose_name='ТС')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicensePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='drivers/driving_license_photos/', verbose_name='Фото прав')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.driver', verbose_name='Водитель')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='drivers/photos/', verbose_name='Фото водителя')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.driver', verbose_name='Водитель')),
            ],
        ),
    ]
