# Generated by Django 4.1.7 on 2023-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0021_alter_vehicle_registration_certificate_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_certificate_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/registration_certificates/', verbose_name='Скан СТС'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/vehicle_passports/', verbose_name='Скан ПТС'),
        ),
    ]
