# Generated by Django 4.1.7 on 2023-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0023_remove_rent_status_delete_rentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
