# Generated by Django 4.1.7 on 2023-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0024_alter_rent_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
