# Generated by Django 4.1.7 on 2023-05-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0025_driver_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=300, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Локация автомобилей',
                'verbose_name_plural': 'Локации автомобилей',
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
                ('is_active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Статус ТС',
                'verbose_name_plural': 'Статусы ТС',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='references.vehiclelocation', verbose_name='Место базирования'),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='references.vehiclestatus', verbose_name='Статус'),
        ),
    ]
