# Generated by Django 4.1.7 on 2023-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0027_vehicle_rent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
