# Generated by Django 4.1.7 on 2023-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0028_rent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='payment_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
