# Generated by Django 4.1.7 on 2023-06-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(null=True, verbose_name='Время')),
                ('summ', models.FloatField(verbose_name='Сумма')),
                ('balance', models.FloatField(null=True, verbose_name='Баланс')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='references.driver', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренда',
            },
        ),
    ]
